auth:
  region: ${region}
  tenancy: ${tenancy}
  compartment: ${compartment}
  user: ${user}
  key: ${key}
  fingerprint: ${fingerprint}

loadBalancer:
  # disableSecurityListManagement disables the automatic creation of ingress
  # rules for the node subnets and egress rules for the load balancers to the
  # node subnets.
  #
  # If security list management is disabled, then it requires that the user
  # has setup a rule that allows inbound traffic to the appropriate ports
  # for kube proxy health port, node port ranges, and health check port ranges.
  # E.g. 10.82.0.0/16 30000-32000
  disableSecurityListManagement: false

  # subnet1 configures one of two subnets to which load balancers will be added.
  # OCI load balancers require two subnets to ensure high availability.
  subnet1: ${subnet1}

  # subnet2 configures the second of two subnets to which load balancers will
  # be added.  OCI load balancers require two subnets to ensure high
  # availability.
  subnet2: ${subnet2}
