#
# CI Pipeline example cluster configuration details
#

label_prefix = "wercker-ci-tf-installer-"
vcn_dns_name = "k8soci"
domain_name = "k8soci.oraclevcn.com"
control_plane_subnet_access = "public"
k8s_master_lb_access = "public"
etcd_lb_enabled = "true"
etcdShape = "VM.Standard1.8"
k8sMasterShape = "VM.Standard1.8"
k8sWorkerShape = "BM.DenseIO1.36"
etcdAd1Count = "1"
etcdAd2Count = "0"
etcdAd3Count = "0"
k8sMasterAd1Count = "1"
k8sMasterAd2Count = "0"
k8sMasterAd3Count = "1"
k8sWorkerAd1Count = "1"
k8sWorkerAd2Count = "1"
k8sWorkerAd3Count = "0"
etcdLBShape = "400Mbps"
k8sMasterLBShape = "400Mbps"
etcd_cluster_ingress = "10.0.0.0/16"
etcd_ssh_ingress = "10.0.0.0/16"
master_ssh_ingress = "10.0.0.0/16"
worker_ssh_ingress = "10.0.0.0/16"
master_https_ingress = "0.0.0.0/0"
worker_nodeport_ingress = "0.0.0.0/0"
